package com.systemdesignlab.platform.shared;

import java.util.UUID;

/**
 * Opaque correlation token used to tie related log lines and operations together across a
 * request or use-case execution.
 *
 * <p>ADR-010 requires every API error response to carry a {@code correlationId}. This value type
 * is the domain/application-level primitive that later work packages build on; it deliberately
 * says nothing about HTTP headers, MDC, or trace exporters -- propagating it through a transport
 * is observability/transport plumbing left to the work packages that actually wire one in
 * (WP-11, WP-15, WP-16). WP-03 provides only the value type itself.
 *
 * <p>Unlike {@link DomainId}, a correlation id is not necessarily generated by this system: it
 * may arrive from an upstream caller and is not required to be a UUID, only a non-blank opaque
 * token. When this system originates one, {@link #generate()} uses a random UUID string for
 * convenience, but {@link #of(String)} accepts any non-blank value so an inbound token can be
 * reused as-is.
 */
public final class CorrelationId {

    private final String value;

    private CorrelationId(String value) {
        this.value = value;
    }

    /** Generates a new correlation id for a request/use case this system originates. */
    public static CorrelationId generate() {
        return new CorrelationId(UUID.randomUUID().toString());
    }

    /** Wraps an existing, possibly externally supplied, correlation token. */
    public static CorrelationId of(String value) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("correlation id must not be blank");
        }
        return new CorrelationId(value);
    }

    public String value() {
        return value;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof CorrelationId other)) {
            return false;
        }
        return value.equals(other.value);
    }

    @Override
    public int hashCode() {
        return value.hashCode();
    }

    @Override
    public String toString() {
        return value;
    }
}
